// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCE8cX5Xaj9UjShdDXtHMJ4WBiFtfyVk',
    appId: '1:860xxxxxxxx7:web:cxxxxxxxxf7a8270a74d46',
    messagingSenderId: '860528877107',
    projectId: 'vert-brasaweb',
    authDomain: 'vert-brasaweb.firebaseapp.com',
    storageBucket: 'vert-brasaweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtJiAF0W6veyHcdc69A4-mSrreBg66ISk',
    appId: '1:8605xxxxxxxx:android:fxxxxxxxxf076d1ea74d46',
    messagingSenderId: '860528877107',
    projectId: 'vert-brasaweb',
    storageBucket: 'vert-brasaweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOn863Nit0-csm38a3MQIGk6xKkepS3Gw',
    appId: '1:8605xxxxxxxx:ios:9xxxxxxxx389f99da74d46',
    messagingSenderId: '860528877107',
    projectId: 'vert-brasaweb',
    storageBucket: 'vert-brasaweb.appspot.com',
    androidClientId:
        '860528877107-a58evr0a3gbp9kn6heb6uvn75do2m59b.apps.googleusercontent.com',
    iosClientId:
        '860528877107-3l28udgsf87hrbk2dhplohv7302f0iq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertBwebApp',
  );
}
